[package]

name = "tinshel"
version = "0.0.1"
authors = ["Liam Marshall <archimedespi3141@gmail.com>"]

[dependencies]
linenoise-rust = "0.1.2"
log = "0.1.10"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"